### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by AdamClearCode** [AdamClearCode/github-crash-course#1]
I thinks it loooks better if the main title is a bit more orange.

The stylinng rule could be changed like this:
```css
h1 {
  color: #efa82e;
}
```
